### PR TITLE
Dev/add nix pkg

### PR DESCRIPTION
**Pull request by wucke13**
### Pull Request Overview

This pull request adds nix pkg for the wasm-interpreter
### Testing Strategy

nix build .#wasm-interpreter

### TODO or Help Wanted

This pull request still needs...

### Formatting

- [x] Ran `cargo fmt`
- [x] Ran `cargo check`
- [x] Ran `cargo build`
- [x] Ran `cargo doc`
- [x] Ran `nix fmt`
- [x] Ran `treefmt`

### CODE REVIEW

**Comment by george-cosma** [comment]
I tried this PR out by creating a docker container with the `nixos/nix` image, and attaching my local fork as a volume. I tested it by running `nix build .#wasm-interpreter --print-build-logs` , exactly how the workflow does it. While it did run the rust tests, it didn't generate any coverage file, in spite of what the output messages told me. Is it an issue with my setup?

**Comment by george-cosma** [comment]
Nevermind, I deleted and re-created the container and now the results are there. My bad!

**Comment by wucke13** [comment]
@george-cosma I added a report pkg, which contains all the HTML reports and a very brief landing page. Maybe we can use this with the PR preview action, so that we don't need the labels to decide which we show (requirements, or coverage), instead we always show everything. However, I'm not quite understanding how the action works in detail, so your expertise would be valueable to make that work!

**Review by george-cosma — DISMISSED** [review]

**Review by george-cosma — APPROVED** [review]

**Review by nerodesu017 — APPROVED** [review]
lgtm

**Comment by george-cosma** [comment]
@wucke13 I'll let you press the "Merge when ready" button if you're also happy with it

**Pull request merged**
